# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
target 'Douyu' do
 
	
  # Pods for Douyu
  pod 'Alamofire', '~> 4.2.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'Kingfisher', '~> 3.2.2'
end
